# Generated by Django 5.1 on 2024-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default='')),
                ('date_of_birth', models.IntegerField(default='')),
                ('PhoneNumber', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
