# Generated by Django 5.1 on 2024-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0002_remove_information_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Age', models.CharField(default='', max_length=30)),
                ('DOB', models.CharField(default='', max_length=30)),
                ('PhoneNo', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='information',
        ),
    ]
