# Generated by Django 5.1 on 2024-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0003_userdatas_delete_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Age', models.CharField(default='', max_length=30)),
                ('DateOfBirth', models.CharField(default='', max_length=30)),
                ('PhoneNumber', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=30)),
                ('Mail', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDatas',
        ),
    ]
